#server:
  #port: 0
spring:
  application:
    name: json-node-tree
  # Banner
  main:
    banner-mode: console
  output:
    ansi:
      enabled: always
  #Security
  security:
    user:
      name: user
      password: default
  ## Datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_json_node_tree?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  ## JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    # dev only set to true for debugging purposes
    show-sql: true
    ## JPA - HIBERNATE
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    #defer-datasource-initialization: true
    open-in-view: false
  # H2 Database
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
        web-admin-password: 1234
  jackson:
    default-property-inclusion: non_null