#server:
  #port: 0
spring:
  application:
    name: json-node-tree
  # Banner
  main:
    banner-mode: console
  output:
    ansi:
      enabled: always
  #Security
  security:
    user:
      name: user
      password: default
  ## Datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_json_node_tree?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  ## JPA
  jpa:
    #database-platform: org.hibernate.dialect.MySQLDialect
    # dev only set to true for debugging purposes
    show-sql: true
    ## JPA - HIBERNATE
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
logging:
  level:
    root: debug
management:
  endpoints:
    jackson:
      isolated-object-mapper: false
    web:
      exposure:
        include: health,metrics,info
        exclude: env,loggers
  endpoint:
    shutdown:
      enabled: false
    loggers:
      enabled: true
